// import type { Metadata } from "next";
// import { Be_Vietnam_Pro } from "next/font/google";
// import "./globals.css";

// // Be Vietnam Pro font import
// const beVietnamPro = Be_Vietnam_Pro({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"], // jitne weights chahiye
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${beVietnamPro.className} antialiased`}>
//         {children}
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import { DM_Sans } from "next/font/google"; // 👈 DM Sans import
import "./globals.css";

// DM Sans font import
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // jitne weights chahiye
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
